version: '3'
services:

  db-postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - db_postgres:/var/lib/postgresql/data

volumes:
  db_postgres: